### ISSUE TITLE
Postman Test Token오류

### ISSUE THREAD

**Issue by leawvc** [Side-Challenge-Study-Time/StudyTime_BE#12]
**Spring Boot 오류 내역**
org.springframework.security.authentication.BadCredentialsException: throw new exception
	at com.challenge.studytime.global.jwt.filter.JwtAuthenticationFilter.doFilterInternal(JwtAuthenticationFilter.java:56) ~[main/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.26.jar:5.3.26]

**Postman 오류 내역**
{
    "timestamp": "2023-04-09T09:42:50.382+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/coupon-history/3"
}

**Bearer Token 사용**

**Comment by KMGeon** [comment]
아마도 jwt token에 대한 오류인 거 같습니다. security config에 url을 확인을 하시거나 회원가입 -> 로그인이 제대로 하여서 token을 올바르게 얻었는지 확인을 하는 게 좋은 거 같습니다.

**Comment by leawvc** [comment]
> 아마도 jwt 토큰에 대한 오류인 경우입니다. security config에 url을 확인하거나 회원가입 -> 로그인이 되어서 서 토큰을 작동시키거나 확인을 하는 것이 좋은 사이트입니다.

해당 부분에서  security config에 url을 넣어 추가해보았지만 똑같은 오류가 발생했습니다.

로그인에는 문제가 없으나  아래의 방식으로 시도 했을 때 GET방식으로 유저의 정보 값이 불러와지는 것을 확인 하였으나 **쿠폰 발급을 하는 URL에서는 500번 에러가  나왔습니다.** 혹시 다른 참고할 만한 곳도 존재할까요
```
.mvcMatchers(POST, "/coupon-history/**").hasAnyRole("USER", "CUSTOMER")
.mvcMatchers(GET, "/**").hasAnyRole("USER", "CUSTOMER")
```

**Comment by KMGeon** [comment]
> > 아마도 jwt 토큰에 대한 오류인 경우입니다. security config에 url을 확인하거나 회원가입 -> 로그인이 되어서 서 토큰을 작동시키거나 확인을 하는 것이 좋은 사이트입니다.
> 
> 해당 부분에서 security config에 url을 넣어 추가해보았지만 똑같은 오류가 발생했습니다.
> 
> 로그인에는 문제가 없으나 아래의 방식으로 시도 했을 때 GET방식으로 유저의 정보 값이 불러와지는 것을 확인 하였으나 **쿠폰 발급을 하는 URL에서는 500번 에러가 나왔습니다.** 혹시 다른 참고할 만한 곳도 존재할까요
> 
> ```
> .mvcMatchers(POST, "/coupon-history/**").hasAnyRole("USER", "CUSTOMER")
> .mvcMatchers(GET, "/**").hasAnyRole("USER", "CUSTOMER")
> ```

지금 mvcMatchers에 hasAnyRole가 USER, CUSTOMER로 설정이 되어있습니다. 현재 프로젝트를 보면 권한을 ENUM으로 관리를 하고 있습니다. ROLE_USER 및 특정 권한을 제대로 설정해야지 올바르게 동작이 된다고 생각합니다.
일단 오류를 해결을 위해 URL을 추가하고 PermitAll로 실행을 해보는 걸 추천드립니다.

**Comment by leawvc** [comment]
> > > 아마도 jwt 포인터에 대한 오류인 경우입니다. security config에 url을 확인하거나 회원가입 -> 로그인이 깃 서기를 작동시키거나 확인을 하는 것이 좋은 사이트입니다.
> > 
> > 
> > 해당 부분에서 security config에 url을 추가해 보았지만 거의 오류가 발생했습니다.
> > 스마트폰에는 문제가 되지 않았거나 아래의 방식으로 시도했을 때 GET 방식으로 사용자의 정보 값이 불러와지는 것을 확인하고 배터리 쿠폰 **발급을 하는 URL에서는 500번 복제가 진행됩니다. **다른 참고할 만한 곳에서
> > ```
> > .mvcMatchers(POST, "/coupon-history/**").hasAnyRole("USER", "CUSTOMER")
> > .mvcMatchers(GET, "/**").hasAnyRole("USER", "CUSTOMER")
> > ```
> 
> 지금 mvcMatchers에 hasAnyRole가 USER, CUSTOMER로 설정이 되어 있습니다. 현재 프로젝트를 볼 수 있는 권한을 ENUM으로 관리하고 있습니다. ROLE_USER 및 특정 권한을 미세하게 설정해야지 생생한 동작이 지나치게 생각됩니다. 한 번 오류를 해결하기 위해 URL을 추가하고 PermitAll로 실행을 해보는 추천드립니다.

PermitAll로 실행 했을 경우 똑같은 에러를 발생시키고 있습니다.
@PathVariable로 CouponId를 가져오기에 /coupon-history/**로 인식이 되지 않는가 하여 URL 을 /coupon-history/3으로 지정하고 실행시켰지만 똑같은 부분에서 에러가 발생하고 있기에 로직에서의 문제점인 것을 파악했습니다.

그렇기에 로직을 모두 검열하고 순차적으로 실행 한 결과 아래의 로직의 문제인 것을 파악했습니다. 감사합니다
```
 if (couponHistoryRepository.existsCouponHistoriesByCoupon_IdAndAndMember_Id(coupon, member)){
     throw new RuntimeException("이미 발급한 쿠폰입니다.");
}
```
